name: GraalVM Community Edition build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build
        run: |
          keytool -import -keystore $GRAALVM_HOME/lib/security/cacerts -alias kamehouse-bundle -trustcacerts -file ./cert/certificate.crt --noprompt
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          mvn -Pnative native:compile -Dmaven.test.skip=true
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: integrationkarafka-${{ matrix.os }}
          path: target/*